In [1]:
%load_ext autoreload

# Examen
## Gauss-Jacobi y Gauss-Seidel

In [2]:
%autoreload 2
from src import eliminacion_gaussiana, matriz_aumentada
A = [[1, 1], [-2, 5]]
b = [7, 0]
eliminacion_gaussiana(matriz_aumentada(A, b))

[07-19 20:37:06][INFO] 2024-07-19 20:37:06.357973
[07-19 20:37:06][INFO] 2024-07-19 20:37:06.452885
[07-19 20:37:06][INFO] 2024-07-19 20:37:06.454584
[07-19 20:37:06][INFO] 
[[ 1.  1.  7.]
 [ 0.  7. 14.]]


array([5., 2.])

In [30]:
%autoreload 2
from src import gauss_jacobi
A = [[1, 1], [-2, 5]]
b = [7, 0]
n = len(A)

x,h = gauss_jacobi(A=A, b=b, x0=[0]*n, tol=1e-5, max_iter=1000)
print(h [0], 'history')


[07-19 21:03:36][INFO] 2024-07-19 21:03:36.484638
[[7.]
 [0.]] x  [<built-in method copy of numpy.ndarray object at 0x0000025A7333D590>]  historua
[[7. ]
 [2.8]] x  [<built-in method copy of numpy.ndarray object at 0x0000025A7333D590>, <built-in method copy of numpy.ndarray object at 0x0000025A7333D1D0>]  historua
[[4.2]
 [2.8]] x  [<built-in method copy of numpy.ndarray object at 0x0000025A7333D590>, <built-in method copy of numpy.ndarray object at 0x0000025A7333D1D0>, <built-in method copy of numpy.ndarray object at 0x0000025A73D8FCF0>]  historua
[[4.2 ]
 [1.68]] x  [<built-in method copy of numpy.ndarray object at 0x0000025A7333D590>, <built-in method copy of numpy.ndarray object at 0x0000025A7333D1D0>, <built-in method copy of numpy.ndarray object at 0x0000025A73D8FCF0>, <built-in method copy of numpy.ndarray object at 0x0000025A73D8F9F0>]  historua
[[5.32]
 [1.68]] x  [<built-in method copy of numpy.ndarray object at 0x0000025A7333D590>, <built-in method copy of numpy.ndarray obje


![alt text](assets/trayectoria.png)


## Grafique

## Use otra estimación inicial
$ x_0 = (1, 1)$

# Grafique

## Gauss-Seidel

In [13]:
%autoreload 2
from src import gauss_seidel
# ---------- 
A = [[1, 1], [-2, 5]]
b = [7, 0]
n = len(b)
gauss_seidel(A=A, b=b, x0=[0]*n, tol=1e-5, max_iter=1000)


[07-19 20:53:17][INFO] i= 0 x: [0. 0.]
[07-19 20:53:17][INFO] i= 1 x: [[7.  2.8]]
[07-19 20:53:17][INFO] i= 2 x: [[4.2  1.68]]
[07-19 20:53:17][INFO] i= 3 x: [[5.32  2.128]]
[07-19 20:53:17][INFO] i= 4 x: [[4.872  1.9488]]
[07-19 20:53:17][INFO] i= 5 x: [[5.0512  2.02048]]
[07-19 20:53:17][INFO] i= 6 x: [[4.97952  1.991808]]
[07-19 20:53:17][INFO] i= 7 x: [[5.008192  2.0032768]]
[07-19 20:53:17][INFO] i= 8 x: [[4.9967232  1.99868928]]
[07-19 20:53:17][INFO] i= 9 x: [[5.00131072 2.00052429]]
[07-19 20:53:17][INFO] i= 10 x: [[4.99947571 1.99979028]]
[07-19 20:53:17][INFO] i= 11 x: [[5.00020972 2.00008389]]
[07-19 20:53:17][INFO] i= 12 x: [[4.99991611 1.99996645]]
[07-19 20:53:17][INFO] i= 13 x: [[5.00003355 2.00001342]]
[07-19 20:53:17][INFO] i= 14 x: [[4.99998658 1.99999463]]
[07-19 20:53:17][INFO] i= 15 x: [[5.00000537 2.00000215]]


array([[4.99999785],
       [1.99999914]])

## Grafique el método de Gauss-Seidel


# Resuelva

$ x_1 + x_2 = 6$

$  -2 x_1 +  x_2 = 0$

In [14]:
%autoreload 2
from src import gauss_seidel
# ---------- 
A = [[1, 1], [-2, 5]]
b = [7, 0]
n = len(b)
gauss_seidel(A=A, b=b, x0=[0]*n, tol=1e-5, max_iter=1000)

[07-19 20:56:46][INFO] 2024-07-19 20:56:46.971904
[07-19 20:56:46][INFO] i= 0 x: [0. 0.]
[07-19 20:56:46][INFO] i= 1 x: [[7.  2.8]]
[07-19 20:56:46][INFO] i= 2 x: [[4.2  1.68]]
[07-19 20:56:46][INFO] i= 3 x: [[5.32  2.128]]
[07-19 20:56:46][INFO] i= 4 x: [[4.872  1.9488]]
[07-19 20:56:46][INFO] i= 5 x: [[5.0512  2.02048]]
[07-19 20:56:46][INFO] i= 6 x: [[4.97952  1.991808]]
[07-19 20:56:46][INFO] i= 7 x: [[5.008192  2.0032768]]
[07-19 20:56:46][INFO] i= 8 x: [[4.9967232  1.99868928]]
[07-19 20:56:46][INFO] i= 9 x: [[5.00131072 2.00052429]]
[07-19 20:56:46][INFO] i= 10 x: [[4.99947571 1.99979028]]
[07-19 20:56:46][INFO] i= 11 x: [[5.00020972 2.00008389]]
[07-19 20:56:46][INFO] i= 12 x: [[4.99991611 1.99996645]]
[07-19 20:56:46][INFO] i= 13 x: [[5.00003355 2.00001342]]
[07-19 20:56:46][INFO] i= 14 x: [[4.99998658 1.99999463]]
[07-19 20:56:46][INFO] i= 15 x: [[5.00000537 2.00000215]]


array([[4.99999785],
       [1.99999914]])